#ifndef ___MY_DEF___
#define ___MY_DEF___

#define MENU_LEN 5

#define MAX_QUEUE_SIZE 1005
#define QUEUE_SIZE 100

#define QUEUE_TABLE_WIDTH 98

#define FIRST_FIELD_WIDTH 18
#define SECOND_FIELD_WIDTH 15
#define THIRD_FIELD_WIDTH 22

#define FIRST_MACHINE_START_WORK_TIME 0
#define FIRST_MACHINE_FINISH_WORK_TIME 6

#define SECOND_MACHINE_START_WORK_TIME 1
#define SECOND_MACHINE_FINISH_WORK_TIME 8

#define MIN_PROB 0
#define PROB 7
#define MAX_PROB 10

#define MAX_REQUESTS_COUNT 1000
#define SEP_REQUEST_NUM 100

#define MEAS_COUNT 16

#define MEAS_TABLE_WIDTH 75
#define FIRST_SECOND_MEAS_FIELD_WIDTH 19
#define THIRD_MEAS_FIELD_WIDTH 18
#define FOURTH_MEAS_FIELD_WIDTH 14

#define TRUE 1
#define FALSE 0

#define RESET "\033[0m"
#define RED "\033[1;31m"
#define GREEN "\033[1;32m"
#define PURPLE "\033[1;35m"
#define BLUE "\033[1;36m"

#endif // ___MY_DEF___